### ISSUE TITLE
love.keypressed holds down the "backspace" key on android

### ISSUE THREAD

**Issue by slime73** [love2d/love#1250]
**[Original report](https://bitbucket.org/rude/love/issue/1245) by Johnathan Sherbert (Bitbucket: [databrain](https://bitbucket.org/databrain), GitHub: [databrain](https://github.com/databrain)).**

----------------------------------------

**Edit**: this seems to be device-specific, using [this code as a repro](https://hastebin.com/raw/qoraronate).

When I first enable text input by love.keyboard.setTextInput(true), and I press the "backspace" key on my on-screen keyboard, love.keyboard.keypressed will register that the key was pressed, and fire with "backspace" as the first argument.

Once it has fired for the first time, however, it will no longer fire again, and love.keyboard.isdown("backspace") will always return true. This happens whether you use love.keyboard.setTextInput() to set the text input on and off. The backspace will appear to be held until you exit the program.

My phone's love version is 0.10.2, Android version is 5.1.1, Model is Kyocera E6782, and software version is Verizon's 2.998VZ

**Comment by MikuAuahDark** [comment]
In my testing, `love.keyboard.isDown("backspace")` is 99% `false`, yes 99% because sometimes it return `true`. And also in my phone holding backspace spams `love.keypressed("backspace")`. Here's the testing code.

```lua
local time = 0

function love.update(dt)
	time = math.max(time - dt, 0)
end

function love.draw()
	love.graphics.print("Backspace? "..tostring(love.keyboard.isDown("backspace")), 12, 12)

	if time > 0 then
		love.graphics.print("Backspace was pressed", 12, 26)
	end
end

function love.mousereleased()
	love.keyboard.setTextInput(not love.keyboard.hasTextInput())
end

function love.keypressed(k)
	if k == "backspace" then
		time = 0.5
	end
end

function love.keyreleased(k)
	if k == "escape" then
		love.event.quit()
	end
end
```

When I run code above, When I press backspace button, it always wrote "Backspace? false" with rare chance of it flashes to true for a single frame. If I hold it, it always shows "Backspace was pressed" until I release it.

My phone is Mi A1 running Android 9 with GBoard keyboard.

Closed because it could be a device/keyboard-app-specific.
