### ISSUE TITLE
Leaving Fullscreen doesn't restore original window size on Linux

### ISSUE THREAD

**Issue by slime73** [love2d/love#1444]
**[Original report](https://bitbucket.org/rude/love/issue/1439) by pragmaticus (Bitbucket: [pragmaticus](https://bitbucket.org/pragmaticus), GitHub: [pragmaticus](https://github.com/pragmaticus)).**

----------------------------------------

```
love.window.setFullscreen(true, "desktop")
```
followed by

```
love.window.setFullscreen(false)
```

Doesn't restore the original windows size, as stated in the wiki:
*If fullscreen mode is entered and the window size doesn't match one of the monitor's display modes (in normal fullscreen mode) or the window size doesn't match the desktop size (in 'desktop' fullscreen mode), the window will be resized appropriately. The window will revert back to its original size again when fullscreen mode is exited using this function.*

Tested on Ubuntu 18.04

**Comment by anna9191** [comment]
I like your article very much, thanks for sharing the good information we have read.
[hotmail login](http://tuts-plus.com/hotmail-login/)
[gmail login](https://sites.google.com/site/tipstologinup/gmail-login)

**Comment by flamendless** [comment]
This happen as well with window manager such as i3

**Comment by lifeisfoo** [comment]
You can reproduce it using this code:
```
function love.draw()
    love.graphics.setColor(20,255,0,255)
    love.graphics.print("Hello", 100, 100)
  end
function love.keypressed(key, scancode, isrepeat)
    if key == "escape" then
        love.event.quit()
    elseif key == "f" then
        love.window.setFullscreen(true, "desktop")
    elseif key == "g" then
        love.window.setFullscreen(false)
    end
end
```
On Windows 10 it works as expected.

On linux (fedora 33) the fullscreen is removed but without resizing the window (it just add the window bar).

Tested using love 11.3 from appimage and from a locally compiled one.

SDL has a lot of open issues related to that: https://github.com/libsdl-org/SDL/issues?page=2&q=is%3Aissue+is%3Aopen+fullscreen+linux

[SDL_UpdateFullscreenMode source](https://github.com/libsdl-org/SDL/blob/a4ddb175f1f1d832960c830191daaab7eb25638f/src/video/SDL_video.c#L1226)

**Comment by lifeisfoo** [comment]
This is a minimal code to test the `SDL_SetWindowFullscreen` function directly.

```c
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdbool.h>

const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;

int main( int argc, char* args[] )
{
  SDL_Window* window = NULL;	
  SDL_Surface* screenSurface = NULL;
  SDL_Init(SDL_INIT_VIDEO)
  window = SDL_CreateWindow( "Fullscreen test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
                   SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_SHOWN );

	const Uint8 *keys;
	bool keepOpen = true;
	while(keepOpen)
	{
    SDL_Event e;
    while(SDL_PollEvent(&e) > 0)
    {
      switch(e.type)
      {
        case SDL_QUIT:
          keepOpen = false;
          break;
        case SDL_KEYDOWN:
          keys = SDL_GetKeyboardState(NULL);
          if(keys[SDL_SCANCODE_F] == 1) {
            // press "f" to enable fullscreen
            SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);
          } else if(keys[SDL_SCANCODE_G] == 1) {
            // press "g" to disable fullscreen
            SDL_SetWindowFullscreen(window, 0);
          }
          break;
      }
      SDL_UpdateWindowSurface(window);
    }
	}

	SDL_DestroyWindow(window);
	SDL_Quit();
	return 0;
}
```

If you run it with `cc -lSDL2 main.c && ./a.out` on linux/wayland with SDL 2.0.14, it works as expected.

Since love 11.3 calls the same function inside the [`bool Window::setFullscreen`](https://github.com/love2d/love/blob/11.3/src/modules/window/sdl/Window.cpp#L676) function, it's very strange that this doesn't work on linux in the same way as the code above.

When the `bool Window::setFullscreen` is called with `fullscren=false`, the `SDL_SetWindowMinimumSize` is invoked just after the `SDL_SetWindowFullscreen`:

```c
	if (SDL_SetWindowFullscreen(window, sdlflags) == 0)
	{
		SDL_GL_MakeCurrent(window, context);
		updateSettings(newsettings, true);

		// Apparently this gets un-set when we exit fullscreen (at least in OS X).
		if (!fullscreen)
			SDL_SetWindowMinimumSize(window, settings.minwidth, settings.minheight);

		return true;
	}
```

That function call was added in [this commit](https://github.com/love2d/love/commit/7b8af113daa511f986769ed021c1bec69c1134ff#diff-9a00c16abbea2bfd22c8e39b3c4b2647a3e90733710b07760a9927e3784155d1R662-R665).

Adding a `SDL_SetWindowMinimumSize` call in the C example, **just after** the `SDL_SetWindowFullscreen`  reproduce the same behaviour of love (exit fullscreen without a window resize):

```c
} else if(keys[SDL_SCANCODE_G] == 1) {
	// press "g" to disable fullscreen
	SDL_SetWindowFullscreen(window, 0);
	SDL_SetWindowMinimumSize(window, SCREEN_WIDTH, SCREEN_HEIGHT); // <--- add this
}
```

If love is compiled with the `SDL_SetWindowMinimumSize` call removed, it works as expected and when exiting fullscreen: the window is resized perfectly (using the love code from my previous comment).

______

The [`SDL_SetWindowMinimumSize(SDL_Window * window, int min_w, int min_h)` implementation](https://github.com/libsdl-org/SDL/blob/release-2.0.14/src/video/SDL_video.c#L2179) contains this code:

```c
window->min_w = min_w;
window->min_h = min_h;

if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
    if (_this->SetWindowMinimumSize) {
        _this->SetWindowMinimumSize(_this, window);
    }
    /* Ensure that window is not smaller than minimal size */
    SDL_SetWindowSize(window, SDL_max(window->w, window->min_w), SDL_max(window->h, window->min_h));
}
```

`_this` is the platform specific video object (cocoa, wayland, x, ...) that makes the real window transformation.
If the platform specific `SetWindowMinimumSize` is not available, this function will not be called and only the `SDL_SetWindowSize` is executed.

Love [defaults for `settings.minwidth` and `settings.minheight`](https://github.com/love2d/love/blob/11.3/src/modules/window/Window.h#L259) are 1, so I imagine that when the `SDL_SetWindowMinimumSize` is executed while the `SDL_SetWindowFullscreen(window, 0)` side effects are not really completed in SDL (internal queue, async execution, ... - I don't know SDL internals), the `SDL_max(window->w, window->min_w)` result will be the fullscreen width. In this way the window is not resized, but only the window top bar is displayed.

And SDL 2.0.14 doesn't have a [`SetWindowMinimumSize` for wayland](https://github.com/libsdl-org/SDL/blob/release-2.0.14/src/video/wayland/SDL_waylandvideo.c#L175)...

____

Possible solutions:
- 1: remove the `SDL_SetWindowMinimumSize` call from love `setFullscreen`. It's really needed today? Is just an old workaround for a SDL bug with osx?
- 2: update SDL to the next release. The [wayland `SetWindowMinimumSize`](https://github.com/libsdl-org/SDL/pull/4065/files) has been merged just some weeks ago.

Sorry for the long comment but I was just exploring love and SDL source code.
I hope this helps @slime73

**Comment by slime73** [comment]
Thanks for the detailed investigation! I haven't tested recently but I suspect the `SDL_SetWindowMinimumSize` call is still needed - it's even possible it's needed on more than just macOS too, so my preference is for option 2 (updating SDL once 2.0.16 is released), if that fixes it.

**Comment by lifeisfoo** [comment]
SDL 2.0.16 will be released soon https://github.com/libsdl-org/SDL/blob/main/WhatsNew.txt

**Comment by MikuAuahDark** [comment]
Someone retested this and it's still an issue as of SDL 2.0.20

**Comment by slime73** [comment]
I tested on macOS and recent SDL doesn't seem to need the SetWindowMinSize call after exiting fullscreen, so I removed it. I also opened a bug report on the SDL issue tracker about this problem.
