### ISSUE TITLE
[Windows] No titlebar icon

### ISSUE THREAD

**Issue by slime73** [love2d/love#148]
**[Original report](https://bitbucket.org/rude/love/issue/143) by JulianAssange (Bitbucket: [JulianAssange](https://bitbucket.org/JulianAssange), GitHub: [JulianAssange](https://github.com/JulianAssange)).**

----------------------------------------

The titlebar of the game window doesn't show its icon (uses the generic no-icon icon instead), although the superbar does use the correct icon. This occurs no matter which of the ways to run the game you use. I've attached a screenshot illustrating what I mean.

[Windows 7 64-bit]

**Comment by SHiLLySiT** [comment]
From what I understand in this thread, there seemed to be a bug or quirk with SDL that prevented this change, or made it difficult to do. Since the last post was over 10 years ago, I wanted to check to see if this could be added now? On Windows, it feels a bit strange to need to use 3rd party software to edit the resulting executable just to change the icon.
