### ISSUE TITLE
Selecting audio output

### ISSUE THREAD

**Issue by slime73** [love2d/love#1537]
**[Original report](https://bitbucket.org/rude/love/issue/1532) by Snusmumriken (Bitbucket: [MainTomato](https://bitbucket.org/MainTomato), GitHub: [MainTomato](https://github.com/MainTomato)).**

----------------------------------------

Love at starting selects the default audio output device and it cannot be changed. It can also lead to errors when connecting USB headphones with their own sound card: when default audio device is speakers, and you connect USB-headphones, the sound continues to flow through the speakers. And when headphones is default and you turn them off, the sound stops working. This feature may solve this weird behavior.

**Comment by 3Pills** [comment]
Seconding this as an issue for myself. The lack of audio output selection has been a problem for me when using bluetooth connected speakers as my default device. If they drop connection it will cause the love audio to stop working entirely, and a game restart is necessary.

**Comment by MikuAuahDark** [comment]
> If they drop connection it will cause the love audio to stop working entirely, and a game restart is necessary.

Unfortunately this is OpenAL-soft issue. kcat/openal-soft#533

**Comment by MikuAuahDark** [comment]
I was thinking about this issue and while my PR addresses the disconnection and automatic device selection, it doesn't solve the manual device selection. So, here's my proposal for the manual audio selection feature:

* Have `t.audio.deferred` in `conf.lua` to defer `love.audio` initialization. If this flag is set to `true`, user must initialize the `love.audio` with `love.audio.init`. This flag is `false` by default, which means `love.audio` is initialized with automatic device selection as it was before.
* If deferred initialization is enabled and the `love.audio` is not initialized then calls to all methods except `love.audio.init`, `love.audio.getPlaybackDevices` and `love.audio.isEffectsSupported` will throw an error.
* `love.audio.init(devicename)` initialize the `love.audio` module. The device name can be `nil` (for automatic selection) or a specific string returned from `love.audio.getPlaybackDevices`. This function throws an error if the specific device name can't be opened. **This function can be only called once!**
* `love.audio.getPlaybackDevices()` returns the available playback device string. Usually the first one is the default selected by user.
* `love.audio.getPlaybackDeviceName()` returns the device name.
* `love.audio.reinit(devicename)` re-initialize the `love.audio` subsystem to another playback device. This function is only supported when using OpenAL-soft v1.22.0 or later. This function throws an error if the specific device name can't be opened or if this functionality is not supported.
* `love.audio.isReinitSupported()` returns boolean if audio reinitialization is supported.

Optionally, a manually updated audio (loopback) for non-realtime purpose can be supported with these proposal:
* `love.audio.init(devicename, sample_rate, channels)` accepts 2 additional parameters: `sample_rate` and `channels`. To activate this mode, `love.audio.loopback` variable must be passed as `devicename`. The variable `love.audio.loopback` is only available (set to any truth value) if [ALC_SOFT_loopback](https://openal-soft.org/openal-extensions/SOFT_loopback.txt) extension is supported. Otherwise it's set to `nil`.
* `love.audio.getPlaybackDeviceName()` returns empty string.
* In loopback mode, `love.audio.reinit` is not supported and `love.audio.isReinitSupported()` is false.
* `sounddata = love.audio.update(dt)` tells OpenAL to mix `dt` seconds worth of audio. This function throws error if loopback mode is not used. A function `love.audio.isLoopback()` can be used to check if loopback mode is used. A sound data with sample rate and channel count specified in `love.audio.init` is returned as the result.

**Comment by slime73** [comment]
For selecting output devices, I don't think we really need more than `love.audio.getOutputDevices` and `love.audio.setOutputDevice` (or similar names).

**Comment by hahawoo** [comment]
(This is a response to #1805 but I'll post it here to keep discussion in the same place.)

I had a couple of unimportant thoughts regarding naming consistency...

Instead of `OutputDevice`, the name `PlaybackDevice` might be more consistent with `RecordingDevice`, i.e. it's not `InputDevice`. Is "playback" the opposite of "recording" like "output" is the opposite of "input"? I'm not meaning to say that I think `PlaybackDevice` is or isn't an overall better name, I just wanted to point this out.

Also, the naming of `audiodisconnected` seems inconsistent with `joystickremoved`. But `audioremoved` seems less understandable to me, maybe I'm suggesting `joystickdisconnected`, or maybe I'm not suggesting anything, but I just wanted to point out that they seem related.

**Comment by MikuAuahDark** [comment]
I go with `audiodisconnected` because the extension name used for that feature is `ALC_EXT_disconnect`, so I think it's reasonable to use `audiodisconnected`.

**Comment by slime73** [comment]
> Instead of OutputDevice, the name PlaybackDevice might be more consistent with RecordingDevice, i.e. it's not InputDevice. Is "playback" the opposite of "recording" like "output" is the opposite of "input"?

Personally, playback makes me think of non-interactive audio/video whereas output feels more in line with what love.audio can do. I don't really have strong feelings about it though, and maybe other people have different feelings.

**Comment by MikuAuahDark** [comment]
Implemented in #1805.
