### ISSUE TITLE
QueueableSource:tell() returns only currently played sounndata chunk position.

### ISSUE THREAD

**Issue by slime73** [love2d/love#1546]
**[Original report](https://bitbucket.org/rude/love/issue/1541) by Snusmumriken (Bitbucket: [MainTomato](https://bitbucket.org/MainTomato), GitHub: [MainTomato](https://github.com/MainTomato)).**

----------------------------------------

Minimal example:

```lua
local decoder = love.sound.newDecoder('allstar.mp3', 44100 * 5)
local sr, bd, cc = decoder:getSampleRate(), decoder:getBitDepth(), decoder:getChannelCount()
local source = love.audio.newQueueableSource(sr, bd, cc, 8)

function love.draw()
  while source:getFreeBufferCount() > 0 do
    local data = decoder:decode()
    if not data then return end
      source:queue(data)
      source:play()
  end
  local f = "Time: %.5f tell: %.3f"
  love.graphics.print(  f:format(os.clock(), source:tell()) )
end
```

![](https://bitbucket.org/repo/A6ddy/images/2974560951-timers.gif)
‌

**Comment by raidho36** [comment]
This is intended behavior. You would have to do manual book-keeping either way (i.e. if it returned total playback time instead then you'd have to calculate in-buffer position manually). Since Qsource can't seek to anywhere beyond what's currently buffered, the sensible thing to return was in-buffer position so that it can be used for seeking.

**Comment by zorggn** [comment]
(Just to note, since my github account is missing from the pasted z0r8 posts, it's @zorggn here.)
