### ISSUE TITLE
Support for floor division operator: //

### ISSUE THREAD

**Issue by bferguson3** [love2d/love#1564]
I'm on Ubuntu, running Love 11.3.

As of 11.2, Love2d is presumably Lua 5.2 and 5.3 compatible, but without full integer support and, at minimum the new floor division operator it just errors out when trying to start a game that contains "//".  This is the _idiv metatable.

Is this going to be added? Or is this a limitation of luajit...?

**Comment by slime73** [comment]
love uses LuaJIT by default. LuaJIT is currently based on Lua 5.1, with a couple backwards-compatible features from 5.2 in there as well.

love should work if you recompile it to use Lua 5.3 instead of LuaJIT, but we don't have plans to do so by default. LuaJIT is 2-200x faster than stock Lua, which is pretty important in the context of game code. LuaJIT does support some integer features via its FFI though.

I don't think LuaJIT has immediate plans to implement integer division on Lua numbers.

**Comment by bferguson3** [comment]
@slime73 Gotcha, thanks for the info!
