### ISSUE TITLE
Ability to manipulate ByteData objects with pure-LÖVE

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1594]
I suggested this a while back.

Currently there's no way to modify `ByteData` objects with pure LÖVE code. This is unfortunate in some environments where LuaJIT FFI is not available (when LuaJIT is not used) or very slow (when JIT is disabled).

My proposal is to add overload of `love.data.pack` and `love.data.unpack` which accept existing `Data` object. For `love.data.pack`, it can either return the same `Data` object or return nothing.

I also want to propose "binary reading/writing" (`Data:readInt32`, `Data:writeInt32`, ...) but not sure if my current design approach is good enough.

**Comment by ImagicTheCat** [comment]
I think `love.data.pack` taking a mutable input would be confusing because the rest of the data API is returning allocated data, maybe `love.data.packInto` or similar would be more suited (unless the same is done for all functions).

Also, having two write/read functions for each type and variants (ex: endianness) seems very verbose maintenance-wise and for the user, maybe also why the Lua team took the `struct` / `string.pack/unpack` path.

Why not having two functions for reading/writing arbitrary sequences of bytes from/to a BinaryData object and then using the `pack/unpack` API to format those bytes ? 

The overhead of primitives functions like `Data:readInt32` would probably be significant enough to compare with the overhead of `pack` followed by the string interning/copy. Then if performances can be improved, new functions could be added, but a generic read/write of bytes would still be useful.

**Comment by slime73** [comment]
I've added Data methods for getting sized integer and float values, ByteData methods for the same, a ByteData:setString method, and a variant of love.data.pack which takes an existing ByteData instead of creating a new one.

I thought about the slight inconsistency of love.data.pack optionally taking an existing object and other love.data functions not doing that, but I think it makes sense because the resulting size for the others isn't necessarily easily known beforehand, whereas it's defined by the format string in love.data.pack.

I don't think these sort of methods are the right place for endian swapping. There's already `bit.bswap` in LuaJIT's bit library, or you could make or use another pure Lua function.
