### ISSUE TITLE
is sdl window and glcontext available?

### ISSUE THREAD

**Issue by sonoro1234** [love2d/love#1610]
Hi,

I am the author of https://github.com/sonoro1234/LuaJIT-ImGui
I am not a user of LOVE2D so my knowledge about it is quite limited.

To be able to use it the same way as with LuaJIT alone it would be useful to get `SDL_Window* window` and opengl context from Lua in order to being able to call `bool ImGui_ImplSDL2_InitForOpenGL(SDL_Window* window,void* sdl_gl_context);`
Is that posible?

victor bombi

**Comment by sonoro1234** [comment]
Actually I was able to run LuaJIT-imgui on LOVE2D with this:

main.lua
```Lua
local imgui = require "imgui.sdl"

local ffi = require"ffi"
ffi.cdef[[
typedef struct SDL_Window SDL_Window;
SDL_Window *SDL_GL_GetCurrentWindow(void);
void* SDL_GL_GetCurrentContext(void);
]]
local sdl = jit.os == "Windows" and ffi.load("SDL2") or ffi.C

local instance
love.load = function(table)
	local sdlwindow = sdl.SDL_GL_GetCurrentWindow()
	local openglctx = sdl.SDL_GL_GetCurrentContext()
    instance = imgui.Imgui_Impl_SDL_opengl3()
	instance:Init(sdlwindow, openglctx)
end

love.draw = function()
	instance:NewFrame()
	if imgui.Button("Hello") then print("Hello") end
    instance:Render()
end
```

I am only unsure about sdl_window or openglctx being posibly recreated later and how to detect it

**Comment by MikuAuahDark** [comment]
While that's possible, I strongly discourage using the GL context directly. The context incompatibilities is actually the least of your problems, but your approach does have chance to break in next major version of LOVE, since the rendering backend is not limited to OpenGL anymore. The next major release of LOVE will have Metal (and possibly Vulkan renderer) so relying on GL context is not feasible.

For the events, LOVE consume all the `SDL_Event *` in the `love.event` module. https://github.com/love2d/love/blob/b86151081d7f7abb456e1de81785cbaa0c85756e/src/modules/event/sdl/Event.cpp
Sadly I don't think there's way to intercept it even when hacking your way by doing some vtable manipulation using FFI.

If I have time, I'd probably rewrite https://github.com/MikuAuahDark/love-imgui to be more performant.

**Comment by sonoro1234** [comment]
> The next major release of LOVE will have Metal (and possibly Vulkan) renderer so relying on GL context is not feasible.

There are imgui implementations for Metal and Vulkan also, so the aproach could be the same.

For the events I will stick to `love.keypressed` and similars.

The main advantage of my aproach based on https://github.com/cimgui/cimgui is that all is generated up to date with imgui changes with almost no work

**Comment by sonoro1234** [comment]
> I am only unsure about whether sdl_window or openglctx can be destroyed and recreated later and how to detect it

I have seen that love.window.setMode and love.window.updateMode are the places in which window and context can be recreated
