### ISSUE TITLE
[feature request] Setup tool

### ISSUE THREAD

**Issue by quadroli** [love2d/love#1654]
How about making a setup tool that can be launched and will include all desired plugins to the generated project, kinda like what libgdx has,([modern version of it](https://github.com/tommyettinger/gdx-liftoff)), i find this to be cool cause many are the times i'd have to include files/plugins mid project, leave alone having to write the initial boiler plate code yourself, so yeah, could someone kindly look into this 😇😊

**Comment by FlamingArr** [comment]
Assuming you mean lua libraries by 'plugins', I don't get how a setup tool will let you select 'desired plugins', there are countless amount of libraries out there.

Also love programs (.love) can be used to create builds for any platform officially (or not officially) supported by love, so the platforms thing is not needed in the setup tool either.

Selecting love version from a setup tool sounds weird to me too cause the best it can do is `t.version = blah` in the conf.lua file, the actual love version used will depend on the version of love you run your project in.

In libGDX a bunch of files/folders need to be present in order to have a functional project so a setup tool sounds useful but love only requires you to have the main.lua file in order to have a fully functional project.

**Comment by quadroli** [comment]
Ahhhh, i see, hadn't considered that, from that perspective, interesting, but i thought instead of having to download and add the files for yourself, at least that part could be automated, that would be pretty sweet

**Comment by FlamingArr** [comment]
The problem with that might be, everyone prefers and uses different libraries so just fetching some specific libraries won't be any good.
One solution would be to let the user tell the setup tool what libraries they want, probably by making a config file like libsToImport.json and the setup file will fetch those, create a main.lua and conf.lua file and call it done.
This kind of tool should not be very hard to implement with a bash/python script.

**Comment by quadroli** [comment]
Exactamondo, that is precisely what am saying, user just ticks exactly what they want, the setup tool does the rest, and yes, should be fairly simple to implement, would just love to see some1 do it, i myself aint quite up to the task atm.

**Comment by MikuAuahDark** [comment]
As mentioned by FlamingArr, the modularity of structuring LOVE projects causes something like "setup tool" unnecessary.

LOVE projects can be as simple as single `main.lua` (for quick prototyping) to gigantic directory structure with lots of files and assets. However how those files is structured is entirely depends on the user/developer (they can place 3rd party libs in `lib` or `3rd` or simply in the project root). Also if somehow such setup tool exist, the list of libraries must be updated constantly.

**Comment by quadroli** [comment]
Yep, should be totally optional for some1 to even use it, all depends on what you are working on, and the larger the project, the more feasible the tool becomes, dontchu say?

**Comment by FlamingArr** [comment]
My previous point still stands, if the setup tool provides a interface to check the libraries to import then the list will be infinitely long and it's near impossible to include every lua library in existence to that list.

That being said, as AuahDark commented, everyone uses drastically different project structures, some put the whole code into main.lua; some use main.lua, components and systems folder.
The setup tool can't magically guess the project structure the user might want and providing presets for every single possibility is near impossible.

**Comment by quadroli** [comment]
and that is why it would be totally, 100% optional to use it, and on the part of libraries, if it is so that u fear the vast amount of libraries would make for too long a list, how about just including the top most used libraries alone?
(for each category)

**Comment by slime73** [comment]
I don't think something like that would be able to be maintained by the LÖVE development team. It'd probably become out of date pretty quickly, which can sometimes be worse than not having the feature at all.

**Comment by quadroli** [comment]
hmmm, so maybe if someone just takes it up as a personal project then, would be feasible

**Comment by quadroli** [comment]
Besides, the way am imagining it, assuming the plugins are hosted on GitHub, the one who would configure the tool, would just set it to be downloading packages from a specific repository, that way, no need for manual updating of the files, unless am not seeing something here

**Comment by MikuAuahDark** [comment]
It would be very complex since not all repository is structured same. Most single-file will reside in its repository root, but some may reside in another folder, or even some libraries reside in a folder and that folder (and all of its files) must be added to the project.

I think the reasoning is clear that something like "setup tool" is unnecessary and can be complex, so I'm going to close this.
