### ISSUE TITLE
["Feature" request] officialy migrate to Lua 5.4.2

### ISSUE THREAD

**Issue by jmwielandt** [love2d/love#1673]
Hi, I think is essential for developers to work with the latest stable release while possible in any context, to enjoy the new features, bug fixes and optimizations so, I request to migrate to the latest stable Lua version.

**Comment by slime73** [comment]
LuaJIT is generally considered better than stock Lua for games because of its drastically better performance and the FFI.

LÖVE 11.3 and older uses LuaJIT 2.0 by default on desktops, and LÖVE 11.4 and newer will use LuaJIT 2.1 by default. You're able to recompile the latest LÖVE code to use stock Lua 5.4 instead though, if you wish to do so for your own games.

What advantage do you see with Lua 5.4 that would offset reduced performance and lack of FFI?

**Comment by FlamingArr** [comment]
LuaJIT (even with jit disabled, let alone jit enabled) outperforms Lua5.4, so in terms of speed LuaJIT is favourable rather than 5.4, alhtough 5.4 also has the *sweet* generational gc which luaJIT doesn't.
As for love, both luaJIT and Lua5.4 are supported I think, you can just build it with lua5.4 and it should work.

**Comment by Biep** [comment]
Lua 5.1 does not have the floor (`//`) operation.  That is OK-ish, as trying to use it will simply lead to an error.
But it also has [a huge bug in `__len`](https://stackoverflow.com/questions/25716851/lua-table-length-function-override-not-working), which simply leads to programs not working as they ought, and *that* is very irritating, to say the least.

I understand the need for speed - but please, then push the LuaJIT people to upgrade.  Or if you have access to the source, please do correct the bug yourself, and use that corrected version.

**Comment by zorggn** [comment]
@Biep You don't know yet, but no one tells Mike Pall what to do.

If you want floored division, you do division, then floor the result: `z = math.floor(x/y)`
That said, LuaJIT also lacks the 64bit integer type that later lua versions added, so `//` doubly doesn't make sense to have. (it does have the FFI, through which you can use similar C types though, where `/` *will* behave like integer division.)

Finally, the `__len` thing is not a bug, it's a change in features that came in lua 5.2; i suggest reading part of this page: <https://luajit.org/extensions.htm> specifically the "Extension from Lua 5.2" part containing this blurb:
> Other features are only enabled, if LuaJIT is built with -DLUAJIT_ENABLE_LUA52COMPAT:

Löve, by default, currently isn't built with that flag enabled, so everything listed there won't work how you might expect it to if you're used to lua 5.2 or above.

**Comment by slime73** [comment]
I don't think we have any special influence with Mike Pall. We also decided for now to not build LuaJIT with `LUAJIT_ENABLE_LUA52COMPAT` because we can't guarantee system-provided LuaJIT libraries on Linux will have it, so it'd create situations where people write code that's only compatible with some platforms.

**Comment by Biep** [comment]
Hmm - my reply seems to have disappeared.
First of all, thanks for the answers.  I know how to use `math.floor`, so that problem reduces to some simple rewriting.
`__len` is harder to emulate, but I can use e.g. unary minus and `__unm` instead.  There are not that many unary operators, though, and it makes for misleading code.
I called it a bug, because the code is there, it only is never executed (unless using the debug library one assigns a length to `nil` or so - which is not very useful).  Strings and tables are the things of which one routinely wants to use, and sometimes to redefine, the length.

**Comment by MikuAuahDark** [comment]
In lua 5.1, the `__len` operator can only be used for custom objects, not for tables. For example, it's possible to have `__len` metamethod for LOVE `Data` objects but not for tables.

This is how `#` is defined in Lua 5.1 https://www.lua.org/manual/5.1/manual.html#2.8
```
function len_event (op)
  if type(op) == "string" then
    return strlen(op)         -- primitive string length
  elseif type(op) == "table" then
    return #op                -- primitive table length
  else
    local h = metatable(op).__len
    if h then
      -- call the handler with the operand
      return (h(op))
    else  -- no handler available: default behavior
      error(···)
    end
  end
end
```
Compare it to Lua 5.2 `#` operator https://www.lua.org/manual/5.2/manual.html#2.4
```
function len_event (op)
  if type(op) == "string" then
    return strlen(op)      -- primitive string length
  else
    local h = metatable(op).__len
    if h then
      return (h(op))       -- call handler with the operand
    elseif type(op) == "table" then
      return #op              -- primitive table length
    else  -- no handler available: error
      error(···)
    end
  end
end
```

So the `__len` operator not working on table is **not** a bug.

**Comment by Biep** [comment]
All right - maybe for some inscrutable reason this was intentional.
Defining it on custom objects can indeed be useful, I agree.
(But the code is not *just* for custom objects - it specifically excludes strings (and in 5.1 tables), but includes all other types.
I can see some use for defining the length of a function..
