### ISSUE TITLE
Minimize (hide) LOVE when there's no graphical env (enhancement)?

### ISSUE THREAD

**Issue by tavuntu** [love2d/love#1684]
I'm using LOVE in a minimal Raspbian OS (DietPi to be precise) and love.window.minimize() doesn't do anything, which makes sense to me because there's no window manager. However, I'd find it very useful (and many others hopefully) if we can still somehow hide the window (with anything being executed, including audio, update logic and maybe even listeners, etc.) and just hide it so we can open some other app without the LOVE app getting in the way.

**Comment by zorggn** [comment]
Have you tried turning off the graphics and window modules in the configuration file, conf.lua?

**Comment by slime73** [comment]
You can initialize love without a window by setting `t.window = nil` in love.conf. You won't be able to use any love.graphics API, and window-related events (including input events) won't be received until a window is created.

**Comment by tavuntu** [comment]
Maybe I didn't explain myself. I actually need to interact with the app in a normal way but, at some point, I need to hide it so I can use another one (retroarch in this case).

**Comment by slime73** [comment]
Maybe SDL2's new KMSDRM backend (rather than its older videocore/rpi backend) can do what you want? Lots of its code is very new so you might need to build SDL2 from the latest source to get the most functionality from it.

I'm not very familiar with that stuff, but in general it's handled by SDL2 interfacing with the OS, rather than by love's code itself.

**Comment by tavuntu** [comment]
I'm not really familiar with SDL2 but I'll definitely do some research and I'll let you know if I find something useful, thanks!

**Comment by slime73** [comment]
After looking at the code for both SDL2 backends I don't believe it's possible to keep the window but hide it in either backend:
https://github.com/libsdl-org/SDL/blob/main/src/video/raspberry/SDL_rpivideo.c#L399-L418
https://github.com/libsdl-org/SDL/blob/main/src/video/kmsdrm/SDL_kmsdrmvideo.c#L1429-L1452

You can call love.window.close to completely close the love window without exiting love. The same restrictions apply (you can't use any graphics API, you won't get window/input events, etc). love.window.setMode can be used afterward to create a window again. It doesn't sound ideal compared to having an actual window manager though.

**Comment by tavuntu** [comment]
That seems like a workaround I really could use, I'll try that, thanks again.

**Comment by tavuntu** [comment]
So I'm using this approach:

```lua
_G.onHold = true
  love.window.close()
  os.execute(retroarch)
  love.event.clear()
  love.window.setMode(constants.CANVAS_WIDTH, constants.CANVAS_HEIGHT)
  _G.onHold = false
```

and everything seems to work ok, I'm just a little worried about `os.execute` blocking the main LOVE thread until retroarch is closed, but that shouldn't have any side effects, right?

**Comment by zorggn** [comment]
I believe you could write a minimal thread that listens to a signal from the main thread sent through a channel (without blocking), and do os.execute in that thread so the main one is not blocked... i believe you can even detect when retroarch stops executing, since the thread will stop being blocked by os.execute, so any cleanup you wanna run in the main thread, you can with a signal sent back to it.

**Comment by tavuntu** [comment]
@zorggn that makes sense and I didn't thought about it, thanks.
