### ISSUE TITLE
no highdpi mouse cursor

### ISSUE THREAD

**Issue by jpiringer** [love2d/love#1708]
when i create a new mouse cursor it's always in low resolution on my macOS 10.15.7
or am i missing something?

**Comment by DerpChest** [comment]
What version of löve are you using?

**Comment by jpiringer** [comment]
i am using 11.3

**Comment by illteteka** [comment]
How are you setting up your window? Could you make a test program that shows this bug?

**Comment by slime73** [comment]
Since you're supplying your own image to newCursor, I suppose the best thing would be for you to be able to specify the image's intended DPI scale otherwise it's just making a guess at it (currently it's always guessing 1x DPI scale). SDL has no API for this, so maybe it's worth making a feature request ticket there.

**Comment by slime73** [comment]
SDL3 now has support for this (https://github.com/libsdl-org/SDL/issues/9838)
