### ISSUE TITLE
mouse.isDown() isn't working properly

### ISSUE THREAD

**Issue by InTheProcess** [love2d/love#1709]
I made a button object that can detect when you press the button.  For it to detect if the mouse is down I attempted to use
"love.mouse.isDown(button or 1)".  It didn't get the keypress.  I tried removing the default value "love.mouse.isDown(button)" and I was still unable to detect a mouse button press.  It only works if I use "love.mouse.isDown(1)" etc...

**Comment by zorggn** [comment]
That function needs a mouse button index to work, and i'm assuming you didn't put one into the button variable you're passing it; if you want a callback function that gets called when any mouse button press happens, look into love.mousepressed on the wiki... in any case, without code, this is probably user error.

**Comment by InTheProcess** [comment]
The variable "button" is a numeric value.  Also, I am using the "love.mouse.isDown()" function, not the "love.mousepressed()" event.

**Comment by zorggn** [comment]
And are you using the function in love.update, or anywhere that gets called from love.update?

**Comment by guilleatm** [comment]
The value button you are passing is not a 'default' value, it's a value you have to assign, it refers to the button you are checking, if you haven't assigned it, your solution "love.mouse.isDown(button or 1)" should work properly because 'button' is 'null' but if you say it doesn't work probably you have a button variable with some value like 34 for example, so the function is checking if the button 34 is being pressed, that doesn't happen. Check the 'button' value before this line with a print().

If this is not the problem and you don't care about the button that is being pressed, you can write "love.mouse.isDown(1, 2, 3)" for checking the first 3 buttons of the mouse (you can put all you want).

Remember that doing "love.mouse.isDown(button or 1)" won't check 'button' and 1, it will check 'button' (3 for example) if it is not 'null' and if 'button' is 'null', it will check 1.

See https://love2d.org/wiki/love.mouse.isDown
