### ISSUE TITLE
Density does not change when mass is changed.

### ISSUE THREAD

**Issue by Voltaia** [love2d/love#1740]
Density has to be set manually, even though it is a calculated value of mass/volume. When you change the mass of a physics object, density stays the same.

Edit: On second analysis, I don't think density works at all. Even changing it does not affect the behavior of the physics object.

**Comment by slime73** [comment]
> I don't think density works at all. Even changing it does not affect the behavior of the physics object.

From the wiki's Fixture:setDensity [documentation](https://love2d.org/wiki/Fixture:setDensity), you need to call Body:resetMassData if you want the body's mass to be recalculated based on the new fixture density.

From what I can tell by reading docs, fixture density is used as an input to body mass calculations rather than the other way around. If you override a body's mass to a manually set value, it doesn't use the Fixture densities as inputs for that.
