### ISSUE TITLE
LuaSocket has released version 3.0.0

### ISSUE THREAD

**Issue by Shosoul** [love2d/love#1790]
https://github.com/lunarmodules/luasocket/releases/tag/v3.0.0

Do you think we should put it in Love 12.x?

**Comment by MikuAuahDark** [comment]
I'd like to know if there are any breaking changes between 3.0.0-rc1 and 3.0.0.

**Comment by Shosoul** [comment]
One of them, I suppose, is support for Lua 5.4.3+ and more features all around. There isn't really a good changelog, though there seems to be some more flexibility with TCP options (which is what I'm mainly working with right now), especially when used with Linux.

**Comment by MikuAuahDark** [comment]
Looks like one of the breaking change is reported lunarmodules/luasocket#371

**Comment by Shosoul** [comment]
Interesting. Yea, they'll probably need to sort that stuff out first.

**Comment by slime73** [comment]
love is actually using a more recent version of luasocket than the 3.0rc1 tag (although it's still pretty old now): https://github.com/lunarmodules/luasocket/commit/316a945 - according to the comments of that breaking change issue, the commit which introduced the problem is older than what we use, so by updating to the tagged 3.0.0 release we won't be introducing that issue at least (since it's already there).

**Comment by MikuAuahDark** [comment]
Another issue is reported: lunarmodules/luasocket#375

I probably have to hold the upgrade until the issues are resolved.

**Comment by MikuAuahDark** [comment]
Looks like LuaSocket is "stable enough" and the other issue in question has not getting any reply since, thus it's probably an invalid issue.

**Comment by slime73** [comment]
Implemented via 7a85dc9df55a9b0befb3399a09d3556081b93ac7
