### ISSUE TITLE
love2d saying that a value is nil when it isn't 

### ISSUE THREAD

**Issue by Mathamagic1010** [love2d/love#1795]
i am learning love 2d and i am following one of the tutorials on the wiki called "your first love2d game in 200 lines" but i ran into a problem on part two
i am trying to get user input and move the sprite left and right and i times it by dt and i assigned the value 150 to speed and it is saying that speed is a nil value

heres the code:
conf.lua:
function love.conf(t) 
    t.title = "First Game"
    t.version = "11.4"
    t.window.height = 800
    t.window.width = 480
    t.console = true
end

main.lua:
player = { x = 200, y = 710, speed = 150, img = nil }

function love.load(arg)
    player = love.graphics.newImage("assets/Aircraft_03.png")
end

function love.update(dt)
    if love.keyboard.isDown("escape") then
        love.event.push("quit")
    end

    if love.keyboard.isDown("left", "a") then
        player.x = player.x - (player.speed*dt)
    elseif love.keyboard.isDown("right", "d") then
        player.x = player.x + (player.speed*dt)
    end
end

function love.draw(dt)
    love.graphics.draw(player, player.x, player.y)
end

and the sprite(Aircraft_03.png):
![Aircraft_03](https://user-images.githubusercontent.com/96267636/162626813-9e487143-75d8-4494-8842-45d0218c8a31.png)

**Comment by slime73** [comment]
The `player = love.graphics.newImage(...)` line inside love.load is overwriting the `player` variable declared at the top of the file, so `player.x` and `player.y` no longer exist. You could name the image something else instead.

The forums and discord server have places for getting help with problems in your code, but this github issue tracker is meant to be a space for problems and requests related to love's own source code rather than user code.
