### ISSUE TITLE
Source:tell() with looping streaming sources gets desynced.

### ISSUE THREAD

**Issue by NyakoFox** [love2d/love#1810]
My friend is working on a project where a sound effect plays every beat of a song, which works fine until the song loops.
After the song loops, the sound starts being played slightly before where it should, seeming to get worse every loop.

This can't be an issue with our code since it uses `source:tell()` to get the position of the song. If said function was returning the right values, looping wouldn't affect the syncing at all.

**Comment by slime73** [comment]
Can you upload a .love or audio file that demonstrates the issue?

**Comment by zorggn** [comment]
You do need to note that what you consider the right values from `:tell` might be based on a false assumption; you'll never get a truly accurate value from that (for sync purposes) due to the granularity of that function (and the internals of the library that handles audio)... and even if it was infinitely precise, you probably would need to account for OpenALSoft's own latencies on top of things.

As a first assumption, looping offsets the internal buffer contents (or however it's implemented in OALS), hence the values returned from tell will drift after each loop.

If that is indeed the case, then it's not a bug, just your expectations being wrong about `:tell`.

However, a solution that i do recommend for games that need to sync audio with anything (gameplay or other audio or whatever) is to look into `Queueable Source`s, and use those with manual syncing and buffering; you'll get (samplepoint-) accurate playback, and you can sync stuff based on that.

(Also do join the löve discord, there people can help better with initial issues that may not even be löve bugs...)

**Comment by NyakoFox** [comment]
@zorggn Thanks for the information! I'll upload a testing `.love` anyway since requested but we'll definitely look into `Queueable Source`s.

> Can you upload a .love or audio file that demonstrates the issue?

Here's [soundtest.zip](https://github.com/love2d/love/files/8744059/soundtest.zip) (GitHub doesn't like attaching `.love` files apparently)

Space to seek to 3 seconds before the end of the file, M to stop/start

You can hear after the first loop that it desyncs.

**Comment by slime73** [comment]
Thanks! I added some time drift logging to that test .love which helped me narrow down the main cause and improve it.
