### ISSUE TITLE
Feature Request: There is no way to tell how many lines printf generates

### ISSUE THREAD

**Issue by NotSoSeriouss** [love2d/love#1815]
I wanted to simply draw a rectangle around the result of `love.graphics.printf()` but there is no way to tell how many lines ( `\n` ) it produces.
A solution might be to make the function return the number of lines generated for ease of use

**Comment by MikuAuahDark** [comment]
Hello, you may be looking for [`Font:getWrap()`](https://love2d.org/wiki/Font:getWrap).

**Comment by steveRoll-git** [comment]
You can use [Font:getWrap](https://love2d.org/wiki/Font:getWrap) - you give at a string and a wrap width, and it returns a table of the resulting lines after they've been wrapped. To get the height of the result, you can take the length of this table and multiply it by the font's height.

Also, if you're printing text that doesn't change often, consider using [Text](https://love2d.org/wiki/Text) objects instead of printf, which allow you to store the text in an object that can be drawn with `love.graphics.draw`. Then, you can get its height with the [getHeight](https://love2d.org/wiki/Text:getHeight) method it has.

**Comment by marcotrosi** [comment]
<img width="883" alt="textbox" src="https://user-images.githubusercontent.com/8596795/176995982-3145f5ba-87a8-48e6-9d4e-11d3a48682f9.png">

```
function love.load()
   textposX = 100
   textposY = 100
   boxoffset= 20
   font = love.graphics.getFont()
   fontheight = font:getHeight()
   textwidth, wrappedtext = font:getWrap("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.", 600 )
   textheight = fontheight * #wrappedtext
end

function love.draw()
   love.graphics.setBackgroundColor(1, 1, 1)
   love.graphics.setColor(0, 0, 0)

   -- draw text
   for i,l in ipairs(wrappedtext) do
      love.graphics.printf(l, textposX, textposY+((i-1)*fontheight), textwidth)
   end

   -- draw bounding box
   love.graphics.line(textposX-boxoffset, textposY-boxoffset, textposX+textwidth+boxoffset, textposY-boxoffset)
   love.graphics.line(textposX-boxoffset, textposY-boxoffset, textposX-boxoffset, textposY+textheight+boxoffset)
   love.graphics.line(textposX-boxoffset, textposY+textheight+boxoffset, textposX+textwidth+boxoffset, textposY+textheight+boxoffset)
   love.graphics.line(textposX+textwidth+boxoffset, textposY-boxoffset, textposX+textwidth+boxoffset, textposY+textheight+boxoffset)

end
```
