### ISSUE TITLE
include C header files in Linux Appimage package for third-party C library development

### ISSUE THREAD

**Issue by ImpleLee** [love2d/love#1839]
Currently the most common way to package love2d games on Linux is [through Appimage](https://love2d.org/wiki/Game_Distribution#Distribution_for_Linux), and in our game, we do [repackage the AppImage file](https://github.com/26F-Studio/love-actions-linux) to obtain a new AppImage.
For a good love2d game, sometimes third-party C libraries are necessary; to develop third-party C library, it is necessary to use functions like `lua_*`. Although binary code of these functions is accessible by linking with `liblove.so` (which is included in [the official AppImage]()), the header files that contain their prototypes are not. The absence of these files forces third-party C library developers to use header files obtained from elsewhere that are not guaranteed to be love2d-compatible and can be obsolete once love2d changes its dependencies.
Therefore, I think it is necessary to make the C header files accessible to developers. Developers will need to link with `liblove.so` in AppImage anyway, so why not just include the header files needed for third-party C library development in AppImage?

**Comment by ImpleLee** [comment]
To clarify, this is not asking for a header file to include all available symbols exposed by love2d, but only the header files of the libraries that is necessary for third-party C library development, i.e. lua header files etc.

**Comment by slime73** [comment]
All love versions since its initial release have used a Lua version that's compatible with code (including Lua C library code) that's written for Lua 5.1. I don't imagine that'll change in the future unless LuaJIT has a big philosophy and compatibility change, in which case we'd document it thoroughly.

As far as I understand, on all platforms it's safe and idiomatic (Lua even encourages setting specific linking flags on some operating systems to accommodate this, which love does) to compile a Lua C library using a different Lua library binary file than what you end up using at runtime, as long as the version is compatible. So I don't think this change is really needed in the context of idiomatic Lua C library authoring.

**Comment by ImpleLee** [comment]
OK, we will use lua5.1 for lua C library development.
