### ISSUE TITLE
[Build Failed on RISC-V] Please consider updating autotool scripts

### ISSUE THREAD

**Issue by iamtwz** [love2d/love#1907]
Hi,

This is Jimmy from the ArchLinux RISC-V Team.

The `config.guess` file contained in the source code is too old to build on the latest architecture, such as RISC-V.

This can be fixed by generating new tarball by latest autotools.

Here's a patch below(in ArchLinux PKGBUILD file):

```diff
--- PKGBUILD
+++ PKGBUILD
@@ -12,6 +12,12 @@ depends=('luajit' 'freetype2' 'mpg123' 'openal' 'libvorbis' 'libmodplug' 'sdl2'

+prepare() {
+  cd $pkgname-$pkgver
+  autoupdate
+  autoreconf -fiv
+}
+
```

We propose a one-time fix for this via upstream, which benefits all downstream package maintainers.

Thanks.

**Comment by slime73** [comment]
I think this is only about the generated love linux source-with-automagic-already-run downloads in our releases section, rather than our actual untouched source code, right? In general I don't think we usually change existing older released versions of love unless something is broken with their setup on platforms we already officially support (which does not include RISC-V architectures right now).

**Comment by KnorkFox** [comment]
This is interesting. Sure, Love will compile on hardware with Risc-V architechture. The development is still ongoing in the newest kernels 6.6. because not all is implemented yet.
Debian, Freebsd, Archlinux offichially support Risc-V.
Please integrate it. It will work later.

**Comment by slime73** [comment]
The next release of love (12.0) will use CMake as the primary build system on Linux instead, so I think this issue isn't applicable anymore.
