### ISSUE TITLE
Window is recreated when love.window.setMode or .updateMode is used to resize

### ISSUE THREAD

**Issue by nataliemeow** [love2d/love#1913]
I'm trying to make my game so that the window can only be scaled by integer multiples of 320×224. The problem is that `love.window.setMode` or `love.window.updateMode` recreates the whole window, cancelling the resize. I've tried making use of the LuaJIT FFI to use the low-level SDL functions, but I didn't succeed.

I propose either to create a set of functions to only resize the window (`love.graphics.setWidth`, `love.graphics.setHeight`, `love.graphics.setDimensions`?), or modify `love.window.updateMode` so that the window is not recreated when the only operation done is a window resize.

Using Cinnamon 5.6.8 on X11.

**Comment by nataliemeow** [comment]
> But what do you mean by cancelling the resize, exactly?
The window is resizable, and is recreated as soon as i drag it even a bit, thus stopping me from resizing further.

**Comment by slime73** [comment]
> The window is resizable, and is recreated as soon as I drag it even a bit, thus stopping me from resizing further.

Oh, I see. Some operating systems just issue one resize event at the end.

> Also, what will change regarding this in 12?

love 12 internally changes the window's size instead of destroying and recreating the window, when setMode or updateMode are called.

That being said... I'm not sure programmatically resizing while the user is dragging to resize at the same time would work or be good UX either. You could try a recent build and see how it goes (go to https://github.com/love2d/love/actions?query=branch%3A12.0-development , click on the topmost one and scroll down for premade builds). But it might end up needing someone to make a new feature in SDL like resize begin/end events or an aspect ratio snapping API, if the programmatic resize doesn't work out.

**Comment by slime73** [comment]
I don't have a Linux system to test on (mac and windows both block the main thread while resizing rather than having continuous events), but I think love 12's approach solves this. Let me know if it doesn't!

**Comment by akkartik** [comment]
I've been resizing on Linux (first on Debian-based Ubuntu using X11 and Unity, and now on Arch-based Manjaro using Wayland and fvwm) without any issues. I never saw any sign that you only receive a single resize event at the end, but rather the opposite: [I've been rate-limiting my windows' resize response for a long time.](https://github.com/akkartik/lines.love/commit/ac4879bb850e2ce3ed9830cc3ff4286f36c0bad4). So now I wonder what window manager Cinnamon uses..
