### ISSUE TITLE
Add getControlPoints function to BezierCurve

### ISSUE THREAD

**Issue by Lukcus** [love2d/love#1941]
Currently, you can only get BezierCurves with the getControlPoint iterator function. Could we add a getControlPoints which returns a Lua table of Curve Control points in the following format `{{x = x, y = y},{x = x, y = y}}`? The structure avoids the following format `{ x, y, x, y, x, y }`, where the Lua code would have to reformat it again with a new table, bringing us back to the iterator way of doing things.

**Comment by slime73** [comment]
I don't think any other love API takes or returns a table with the `{{x = x, y = y}, {x = x, y =y}}` format, so adding that wouldn't be very consistent.

In general we try to avoid functions that return big arrays too, since it's less flexible (and in many cases would generate a lot more garbage-collected memory) than a function that takes an index and returns coordinate number values.
