### ISSUE TITLE
Set icon without third party software

### ISSUE THREAD

**Issue by SHiLLySiT** [love2d/love#1965]
I left a comment awhile back on #148 to ask about this, but haven't had a response so opening as a new ticket.

From what I understand in the old thread, there seemed to be a bug or quirk with SDL that prevented being able to set the icon, or at least made it difficult to do. Since the last post was over 10 years ago, I wanted to check to see if this could be added now? On Windows, it feels a bit strange to need to use 3rd party software to edit the resulting executable just to change the icon.

**Comment by slime73** [comment]
It's not really a bug with SDL, I don't think Windows lets an app set a global app icon itself, just a window icon. SDL exposes the latter functionality. It wouldn't even really make sense to set the global icon from inside the app because it would be reset when you closed the app and wouldn't show up on the desktop etc.

In order to set the global icon that the OS will use everywhere, you need to edit or recompile the executable file on Windows. On other platforms the process is slightly different.
