### ISSUE TITLE
GitHub Actions Windows release generation

### ISSUE THREAD

**Issue by BenStigsen** [love2d/love#1971]
It is possible that I've missed it. But is a binary not generated for Windows with GitHub Actions?

**Comment by slime73** [comment]
They are - here's an example of a recent build of the main branch with binaries for windows/mac/linux https://github.com/love2d/love/actions/runs/5918509670#artifacts
And a recent build of the 12.0-development branch https://github.com/love2d/love/actions/runs/6131978659#artifacts

For 11.x (the main branch right now), official release binaries for Windows will use an appveyor build rather than a github actions build since the former still supports VS2013 right now - here's a recent build of that https://ci.appveyor.com/project/slime73/love/builds/48062534

**Comment by BenStigsen** [comment]
All I had to do was scroll down more to see it 🤦‍♂️
Thank you!
