### ISSUE TITLE
[bug] running lua files

### ISSUE THREAD

**Issue by ABoxNinja** [love2d/love#1987]
## Very unclear on how to do it.
Trying to open with love or drag and dropping it in the window doesn't work. Also installation doesn't add the PATH system environment variables, for custom commands.

**Comment by slime73** [comment]
The [Getting Started](https://love2d.org/wiki/Getting_Started) wiki page describes some ways to run a love project. In particular, a project is the whole folder containing main.lua, you need to run that folder instead of main.lua.

That being said, the forums or discord server are better places to ask this sort of question than the bug tracker.
