### ISSUE TITLE
Phase out Autotools Build System

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1991]
During the release of 11.5, we have bit of discussion on switching the Linux build system from Autotools to CMake. This means one build system for every platform we support (except macOS families), although Linux enthusiast users may not happy with this change.

I left this open for further discussion ~~and didn't tag it to specific milestones for same reason~~.

**Comment by bartbes** [comment]
I took a quick look the other day, and this is a (non-exhaustive) list of things I couldn't find in the CMake implementation:

- [ ] Some magic stb_image flag [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/configure.ac#L44). As far as I can tell it's dead code, as I couldn't find any references to `LOVE_STBI_SSE2_OVERRIDE`.
- [ ] An option to disable GME [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/configure.ac#L63). I'm not sure we still need it.
- [ ] Flags to disable specific modules. Again, I'm not sure we need to reproduce it. We probably could with some relatively simple cmake scripting, but I doubt anyone seriously uses it.
- [ ] [Some OSX stuff](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/configure.ac#L36)? Given that it's called "OSX" rather than macOS, and I've never heard anyone talk about it after the initial request, maybe nobody uses it? Looks like homebrew [just grab the published binaries](https://github.com/Homebrew/homebrew-cask/blob/24f7824cccfa4b50c3f2e3d023986816ab34cda9/Casks/l/love.rb)
- [ ] Generating files [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/configure.ac#L135C1-L141C3) and [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/Makefile.am#L17C1-L24C14)
- [ ] A bunch of stuff for `make install` [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/Makefile.am#L3C1-L15C64)

I feel like if we implement the last two, we should be set. I'm sure generating files is as simple as `configure_file`, but I've never dealt with install targets on cmake, and the docs always confuse me.

**Comment by slime73** [comment]
> `LOVE_STBI_SSE2_OVERRIDE`

I think that was for an older version of stb_image. It shouldn't be needed anymore.

> An option to disable GME

We've completely removed GME support (whereas before you could compile love with it enabled but it wasn't build like that by default, at least on Windows/macOS) so that can go too.

**Comment by MikuAuahDark** [comment]
> Generating files [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/configure.ac#L135C1-L141C3) and [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/Makefile.am#L17C1-L24C14)

Are those Debian-specific files still needed? All of the files listed there are at least 5 years old since its last commit. I don't think recent Debian uses those anymore, but I'm not sure.

> A bunch of stuff for make install [here](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/platform/unix/Makefile.am#L3C1-L15C64)

Do they just need to be placed in their respective directories or is there an additional program that needs to be run? I think [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) helps here.

> Flags to disable specific modules. Again, I'm not sure we need to reproduce it. We probably could with some relatively simple cmake scripting, but I doubt anyone seriously uses it.

This is doable, but I'm not sure if we really need it. I remember someone asked in Discord if it's possible to disable specific modules compile-time.

**Comment by slime73** [comment]
Compile-time module disabling isn't really maintained enough to know whether it works as expected right now I think (e.g. I'm not sure which combinations actually compile successfully these days). It'd be nice to polish it up and make it easily supported on all platforms, but maybe that's a separate task with a different priority.

**Comment by bartbes** [comment]
> Are those Debian-specific files still needed? All of the files listed there are at least 5 years old since its last commit. I don't think recent Debian uses those anymore, but I'm not sure.

I use them for ppa builds.

**Comment by bartbes** [comment]
Also requires a change to the appimage repo, see the corresponding PR here: https://github.com/love2d/love-appimage-source/pull/4

**Comment by MikuAuahDark** [comment]
LOVE 12 is no longer using Autotools for Linux build system.

**Comment by a-detiste** [comment]
Hi, Debian used to statically link liblove inside love executable. Is it still possible with CMake ?

**Comment by slime73** [comment]
What sort of situation do you want that for?

**Comment by a-detiste** [comment]
...inertia... that's how other people did setup the autoconf build before me.

`dh_auto_configure -- --disable-shared --enable-static --with-lua=$(LUA_IMPL)`

If you say it's not supported anymore (/ or it never made any sense) it's fine,
we'll build a real `liblove0.so`

**Comment by slime73** [comment]
Having a separate `.so` also lets people load and use love's APIs from a standalone Lua interpreter if they want (although it's pretty rare to want that.)

**Comment by a-detiste** [comment]
I've browsed https://repology.org/project/love/packages and I see that many distro that upgraded to 11.5 are using `platform/unix/automagic` but I don't want to go that way either.

Supporting a CMake build of `love` with the `.so` built-in woudl be the best.

**Comment by a-detiste** [comment]
Ok so I guess I'll use automagic for 11.5 & CMake for 12, thanks for the clarification

```
https://src.fedoraproject.org/rpms/love/raw/rawhide/f/love.spec
https://raw.githubusercontent.com/termux/termux-packages/4291a36de/x11-packages/love/build.sh
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/interpreters/love/11.nix#L34
https://gitlab.com/liguros/liguros-repo/-/raw/develop/games-engines/love/love-11.5.ebuild
https://gitweb.gentoo.org/repo/gentoo.git/plain/games-engines/love/love-11.5.ebuild
```
