### ISSUE TITLE
Missing physfs symbols in LÖVE 11.5 on iOS

### ISSUE THREAD

**Issue by SugarRayLua** [love2d/love#1997]
Hello. 
I'm finding an error on iOS with the attached test program. Here's the main.lua in it:

```
nativefs = require 'nativefs'

function love.load()
  nativefs.createDirectory(love.filesystem.getSourceBaseDirectory()..'/foo/')
end
```

The error I see is:
```
Error
nativefs.lua:345: dlsym(RTLD_DEFAULT, PHYSFS_getMountPoint): symbol not found


Traceback
[love "callbacks.lua"]:228: in function 'handler'
[C]: in function '__index'
nativefs.lua:345: in function 'withTempMount'
nativefs.lua:406: in function 'getInfo'
nativefs.lua:327: in function 'createDirectory'
main.lua:4: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

The attached nativefs.lua is unmodified and was working on iOS with LÖVE 11.4. Has anything changed in the physfs interfaces LÖVE exposes in 11.5? @akkartik reports that this program works fine on Linux.

[mkdir-test.love.zip](https://github.com/love2d/love/files/13694810/mkdir-test.love.zip)

**Comment by slime73** [comment]
love 11.5 hides function symbols that aren't explicitly marked for export, in order to reduce the size of builds.

You can change that behaviour in the xcode project by setting the "Symbols Hidden By Default" option in the liblove and love project build settings to "No" instead of "Yes" (it could cause build sizes to increase by doing that, of course). That being said, the approach taken by the nativefs library only worked accidentally before rather than being an officially supported thing in love, so it might be best to not rely on it.

**Comment by SugarRayLua** [comment]
Thanks!
