### ISSUE TITLE
The filesytem API similar to os.path.join()

### ISSUE THREAD

**Issue by neverchanje** [love2d/love#2000]
Hi folks,

I didn't find any alternative for the API similar to https://docs.python.org/3/library/os.path.html#os.path.join  I searched the issues and didn't find related discussions. 

Given that the implementation is platform-specific, I wonder if we can make it a built-in api rather than letting developers concatenate paths simply by adding '/'.

**Comment by slime73** [comment]
love.filesystem paths are already platform-independent (because they're always relative to the mounted directories - i.e. the game source and save dirs - and they don't have platform-specific separators), so the implementation of a function like that wouldn't be platform-specific and I don't think it'd be too useful for love to provide it.

**Comment by slime73** [comment]
Yep! At least for the love.filesystem functions you'd typically use that work with relative paths, as shown on the love.filesystem wiki page.
