### ISSUE TITLE
Error  main.lua:2: bad argument #1 to 'isDown' (number expected, got string)   Traceback  [love "callbacks.lua"]:228: in function 'handler' [C]: in function 'isDown' main.lua:2: in function 'draw' [love "callbacks.lua"]:168: in function <[love "callbacks.lua"]:144> [C]: in function 'xpcall'

### ISSUE THREAD

**Issue by LeonardNekit** [love2d/love#2002]
src:
function love.draw()
  if love.mouse.isDown('l')then
    love.graphics.print("hello", 10, 200)
  end
end

**Comment by slime73** [comment]
Like the error says, `love.mouse.isDown` expects a button number, rather than the string you're giving it. It's documented in the wiki too: https://love2d.org/wiki/love.mouse.isDown

This issue tracker is meant for problems and changes in love's own source code - the Discord server, forums, or subreddit are more appropriate places to get support for your own code.

**Comment by LeonardNekit** [comment]
Is it possible to display text on the screen?

**Comment by MikuAuahDark** [comment]
Yes, using `love.graphics.print`.

But again, this place is meant for issues within LOVE's source code (or bugs) itself, not for help support.
