### ISSUE TITLE
integration with zig cc

### ISSUE THREAD

**Issue by nacho00112** [love2d/love#2010]
that would make easier to add Zig/C code to love2d projects, `zig cc`'s cross-compilation features are VERY good, good enough to consider this imo

**Comment by slime73** [comment]
Can you describe what doesn't work and what would need to change to make it work? And what sort of goals and specific platforms in mind do you have for cross-compilation? Keeping in mind most people don't ever need to compile love for any platform themselves.

**Comment by flamendless** [comment]
On the top of my mind would be compilation speed if we use Zig 🤔

**Comment by nacho00112** [comment]
Well, I want simply to be able to add optimizations through Zig if I want,
I might get it to work, but I would probably need to do it manually,
I think that's an ugly solution considering that in android I have to
recompile to each architecture, so I want a build system for that,
I'm mentioning the cross-compilation because I believe that it would make
the integration easier, it seems that the Zig compiler managed to compile to android
without the android NDK https://lists.sr.ht/~andrewrk/ziglang/%20%3CCACZYt3T8jACL+3Z_NMW8yYvcJ+5oyP%3Dh1s2HHdDL_VxYQH5rzQ%40mail.gmail.com%3E

**Comment by tpimh** [comment]
I was also under impression that compiling native modules for Android would mean adding like 10 different targets including ARMv6, ARMv7, ARMv8, MIPS32, MIPS64, i686, x86_64 and probably some other...

Turns out I was wrong (I did a little bit of research here: https://github.com/love2d/love/issues/2008#issuecomment-1902276500), and Android only officially supports ARMv8 at the moment, and maybe will also support RV64 in the future.

This means the same tool chain that you use to compile for RPi for example would also work for Android. The only difference is that the binaries need to be linked against bionic instead of glibc.

**Comment by nacho00112** [comment]
x86_64 is for emulator maybe?
and armv* can serve for compatibility with old devices

**Comment by slime73** [comment]
> Well, I want simply to be able to add optimizations through Zig if I want and then use them in lua

What sort of optimizations do you have in mind? Since love uses LuaJIT, your Lua code is JIT-compiled (on platforms where that's supported) and it also has its FFI library so you can directly call C functions or use C data structures.

So far from what's been described here, I don't really have a good picture of practical problems people ran into with current setups and how zig overcomes those problems, and how people imagine changing the compiler toolchain would actually work with love's build setup.
