### ISSUE TITLE
Both key and scankey has some problems on AZERTY keyboards

### ISSUE THREAD

**Issue by Popolon** [love2d/love#2012]
When getting the key and scankey with [love.keypressed(key, scancode, isrepeat)](https://love2d.org/wiki/love.keypressed). Looks like that's a [SDL2 issue](https://wiki.libsdl.org/SDL2/SDL_Scancode)

To understand how an AZERTY keyboard work, numbers are obtained by shift + "number line". (on linux caps + "numbers line"

Default keys, without shift, on this kind of keyboard is:
first line:
<pre><code>
|&|é|"|'|(|-|è|_|ç|à|)|=| AZERTY line1
|1|2|3|4|5|6|7|8|9|0|-|=| QWERTY line1
|a|z|e|r|t|y|u|i|o|p|^|$| AZERTY line2 
|q|w|e|r|t|y|u|i|o|p|[|]| QWERTY line2
</code></pre>
* ^ on AZERTY line 2 is dead key (only return something if

On second range,  scancode is qwerty code, and key is azerty code
On first range, for managed keys, both key and scancode are number, on keys with diacritics (2=é, 7=è, 9=ç, 0=à, nothing is returned at all in both scancode and key.

On the second line, key=a scancode=q, etc but at the end of the line, where ^, there is scancode=[ and key = unknown.

Maybe a way to obtain the raw keycode number as reported by driver would be better for these cases?

**Comment by slime73** [comment]
What OS and love version are you testing with? If you're on Linux, are you using the love AppImage or love installed through a package manager?

**Comment by Popolon** [comment]
This is the last LÖVE version, from package manager (tested on Arch x86_64 and Manjaro Aarch64 (ARM64), but after some verifications, the problem come from libSDL2, verified on other libSDL2 application (TIC-80) and libSDL2 API, I will try to report to libSDL2, and when it is resolved, will close it here.

**Comment by slime73** [comment]
Make sure your version of SDL2 is up to date (the latest release is 2.28.5, and 2.30 is coming shortly). If you use love's AppImage instead of package manager dependencies, then it'll use SDL 2.28.5. I believe there have been several fixes to scancode detection on Linux recently, so I think there's a high chance using the latest version will solve your issue if you have an older version.

**Comment by Popolon** [comment]
ArchLinux packages are always up to date (that's a rolling release), its goal is to upstream bugs instead of adding patch, as most as possible. So yes, this is the latest release, but the bug is very old. I think to invest more time in SDL improvement anyway, encounter some other part where it is behind in term of functionalities on Linux, despite it was first created for Linux around 2000 (lot of good work made since).

**Comment by slime73** [comment]
love now supports a wider range of key constants (everything SDL supports). For the mismatch in the top line of your keyboard, you'll have to bring it up in the SDL issue tracker if you want it changed - it seems like it was intentional but I'm not sure whether it's useful or not.

That being said, text input events (love.textinput) are a much better choice if you just want to get the text that a user is typing.
