### ISSUE TITLE
Request: MeshDrawMode: lines

### ISSUE THREAD

**Issue by heiyu17** [love2d/love#2016]
draw axis, grid, etc.

mesh is more efficient than line, and can be projected to 3D, I really hope löve will implement this in the future.

**Comment by slime73** [comment]
GPU line drawing modes are have a bunch of their own problems - for example they have no antialiasing, no well-supported way to configure line widths, and the method that they use to draw (and therefore the exact pixels that they cover) is different depending on the GPU and graphics driver.

A lot of games and projects tend to use geometry (e.g. two triangles to make a quad) instead of GPU line drawing even when the latter is available, because of those issues. Does that definitely not work for your use cases?

**Comment by heiyu17** [comment]
thank you, now i get it, I don't have much knowledge of graphics, everything need to become triangles, even though line, or calculating it in shader to simulate, sorry for the inconvenience.

**Comment by slime73** [comment]
There's nothing to be sorry about, I just try to be thorough about making sure new love features are as useful and polished in practice as they appear at first glance. :) 

I'm still open to adding this if you (or someone else) has example situations where its downsides matter less than its upsides.
