### ISSUE TITLE
Android Depth Buffer

### ISSUE THREAD

**Issue by kovaxis** [love2d/love#2054]
I cannot seem to get the depth buffer in Android to work.

This is my `conf.lua` file:

```lua
function love.conf(t)
    t.window.depth = 16
    t.window.stencil = 8
end
```

And these are the results (note the wrong overlap):

![image](https://github.com/love2d/love/assets/7827085/f45eb32d-2947-4869-83da-92ce029c8fb7)

The same game works properly on Love2D 11.2 in Linux under Wine and 11.5 natively on Linux, so the issue is likely the depth buffer not being initialized properly on Android.

I'm packaging my app using the [APKTool method](https://love2d.org/wiki/Game_Distribution/APKTool) and testing on a Samsung S20 FE with Android 13.

It doesn't work either with `t.window.depth = 24`.

**Comment by slime73** [comment]
Are you calling love.window.setMode later? If so setMode will override the previously set depth value. Also be sure to use love.graphics.setDepthMode otherwise no depth testing or depth writes will happen.

Or if you're rendering to a Canvas, they don't use the window's depth buffer, you'll need to use the depth parameter of love.graphics.setCanvas.

**Comment by kovaxis** [comment]
Very sorry, I was calling `love.window.setMode` but I hadn't noticed. My fault.

If you don't mind, I will open another issue to improve the documentation on this matter.
