### ISSUE TITLE
remove the arbitrary 10x near/far plane scaling in the default projection matrix

### ISSUE THREAD

**Issue by expikr** [love2d/love#2055]
Currently, the default orthographic projection matrix uses an awkward near/far plane of +/- 10 rather than +/- 1. 

Even with the new custom projection api it's still better to remove this arbitrary esoteric scaling.

**Comment by slime73** [comment]
What benefits would you get from [-1, 1], considering changing it may break a lot of people's projects?

To me, [-1, 1] doesn't seem much less arbitrary than [-10, 10] for an orthographic projection. It's still being scaled if it's [-1, 1], and will always be scaled depending on the platform.

**Comment by slime73** [comment]
> Because [-10, 10] is an undocumented Love2D-only quirk that no other graphics API or framework has.

I plan to document the default projection matrix when I document the APIs for setting a custom projection matrix. But I don't understand the rest of this sentence - every game or engine that has a projection matrix has an input depth range for that matrix. Most input depth ranges in projection matrices are actually not [-1, 1]. That input depth range is usually called near and far clipping planes. I think Unity defaults to a range of [0.3, 1000] or so in its Camera components, for example.

> For those wanting to work with love.graphics.replaceTransform directly without throwing out the shader entrypoint entirely, it means the following compensation matrix must to be applied on top of your typical expected matrix formulation.

The default orthographic projection matrix is already applying a range change along x and y axes, as well as potential y-flips. If you want to 'compensate' for / neutralize love's default projection, you will need to do multiple things aside from a depth change.

love 12 provides `love.graphics.setProjection` so you don't need to use a custom shader and you don't need to "undo" love's projection matrix, if you want. That's the right tool for this job, rather than changing love's default projection matrix just to change what you'd need to do in order to "undo" it.

**Comment by slime73** [comment]
> I'm talking about the scaling to Normalized Device Coordinates, which if unchanged from default is [-1,1] for OpenGL.

Scaling from one input depth range to a different vertex clip space output range is exactly what a projection matrix typically does. You'll rarely find any projection matrix that just has a "pass-through" depth range.

Separately, scaling from a love vertex shader's output values to the graphics backend's expected clip space is handled automatically by love 12. So you don't have to worry about Metal's [0, 1] NDC depth range versus OpenGL's [-1, 1] depth range versus Vulkan's [0, 1] depth range versus the separate y direction for all of those and can just write one shader or one matrix that works everywhere. :)

I may change the expected value there to be [0, 1] instead of [-1, 1] because it allows for more depth precision (OpenGL made some bad choices in its design that were fixed after it was already dying, and it's kind of a shame to retain them), but that's a decision for another day.

**Comment by slime73** [comment]
> That would be ideal, but you must also accompany it with glClipControl otherwise you still get the same poor precision.

On OpenGL yes. On Metal and Vulkan it's already [0, 1] in device clip space, and love is currently converting from [-1, 1] to [0, 1] after the user's vertex shader runs.

> The drawback of this is that it can't work with older GL versions. So you'll need to have two different versions of default projection between versions that support ClipControl and those that don't, otherwise you'll get visibly different clipping behaviours.

No, this is already handled automatically after the user's vertex shader runs, in love 12.

**Comment by slime73** [comment]
Good depth precision is not possible on some versions of OpenGL and is possible on others as well as on Metal and Vulkan. If love is changed to expect [0, 1] and only internally converts to [-1, 1] under the hood when the backend actually needs it (OpenGL without glClipControl available), then it will have good depth precision on every platform where good depth precision is possible.

Currently, with love expecting [-1, 1] it means depth precision is limited even when platforms support better precision.

Either way, there's zero need for people to have different vertex shader outputs on different platforms, because of how love 12 handles things. I took inspiration from webgpu and spirv-cross for that, and I'm glad I did because it works better than some other engines like Unity.

**Comment by slime73** [comment]
It's more like:
* Current love 12 behaviour: same as love 11 in terms of precision and range.
* Possible new behaviour: more precision than love 11 on some platforms, with people having to change their matrices to account for the output range difference.

In any case this is very off-topic and more suited for a discord or forum discussion than an issue report's comments.

**Comment by slime73** [comment]
No, there is no real neutral input depth range for a projection matrix. Their entire purpose is to convert from one coordinate system to another.

> Reusing the current 10x matrix will already cause the behavior to shift to 0,20 anyways so it will still "break" people code by that logic.

Every projection matrix that's meant to be used with depth values *including love's own projection matrix* will need to change if the range is changed. That means the input depth range won't change for matrices that are updated, and anything that uses that input depth range with those matrices will not break.

I really don't like spamming an issue tracker, so I'll lock this now.
