### ISSUE TITLE
Improve documentation about the window's depth buffer

### ISSUE THREAD

**Issue by kovaxis** [love2d/love#2056]
Currently, the window has a depth buffer attached on desktop platforms by default (at least on Linux).
However, on Android at least there is no depth buffer attached by default (it must be enabled in `love.conf` or `love.window.setMode`).

It would be great if all platforms used the same default for the depth buffer.

If the default is no depth buffer, then I think it should be documented in `love.graphics.setDepthMode` that the depth buffer must be enabled for the window in order to draw with depth testing directly to the screen.

If the default has to be different for some reason, it would be great if it was documented somewhere, hopefully everywhere that matters (`love.conf`, `love.window.setMode` and `love.graphics.setDepthMode` come to mind).

**Comment by MikuAuahDark** [comment]
If you have LOVE forum account, you can use the same credentials to login into the [wiki](https://love2d.org/wiki/) and modify the page as needed.

**Comment by slime73** [comment]
> Currently, the window has a depth buffer attached on desktop platforms by default (at least on Linux).
However, on Android at least there is no depth buffer attached by default

love actually requests no depth buffer for the window on all platforms by default. However some unhelpfully allocate one even when none is requested, probably because a stencil buffer is also requested by default and they're usually allocated together.

In love 12, setDepthMode has more explicit errors when depth writes are enabled and no depth buffer has been requested for the window or active set of Canvases.

I've also updated the notice at the top of the setDepthMode wiki page to be more clear.
