### ISSUE TITLE
allow for vectors in positions and sizes

### ISSUE THREAD

**Issue by roroire** [love2d/love#2064]
# Love2d version
11.5
# the problem

setting up value by value is boring, let's get love.graphics.rectangle for example:

```lua
love.graphics.rectangle(mode, x, y, w, h, rx, ry, segments)
-- string: mode
-- number: x, y, w, h, rx, ry, segments
```

there are a few problems there, but the main one is: too many arguments, passing each one by one may be a problem and/or disadvantage for the following reasons:

if you want to make some operation with the object's position, you must do it with x and y, separately, which may be boring to do one by one. solution? use a table with x and y position, and set __mul operators and the like for that table/class. now our problem is mostly solved, except that whenever we want to set anything with position, we must insert that table's x and y separately into the function.

another problem arises: from love.physics, as it changes position by itself, so if we want to operate that object's position by ourselves (let's say, 'teleport'), we must insert x and y again, as changing a table back won't change our object's position.

love.graphics.set color already does something similar:

```lua
love.graphics.setColor(rgb)
-- table: rgb {r, g, b}
```
I propose, instead:

## position and size properties for all drawing and physics:
```lua
love.graphics.rectangle(mode, position, size, radius, segments)
-- mode: string
-- position, size, radius: tables with x and y positions
-- segments: number

-- now suppose a dev makes a collider class like HDictus's breezefield: a class with a .shape, a .body, and a .fixture
player = world:newCollider(type, x, y, w, h)
-- type: string representing the shape of the collider, as Rect, Circle, etc
-- x, y, w, h: numbers
-- note: HDictus's breezefield uses {x, y, w, h} instead, but I prefer to keep in the way Love2d does, and those aren't optional fields
-- player properties: x, y, w, and h

it could simply be:
player = world:newCollider(type, position, size)
-- type: string
-- position: table {x, y}
-- size: table {x, y}

-- player properties:
position {x, y}
size {x, y}
```

with a tool like Hump's vectors, all that math easens the process of calculating position, saving who knows how many wasted time doing solehandedly

and lastly, it should not be an abrupt change, I guess, the old way of (x, y, w, h) should keep usable for a few more releases

**Comment by a13X-B** [comment]
löve does not come with a builtin vector type but there are many libraries that implement vectors fairly differently and giving preference to just one of them won't really solve the problem in general.
you can easily work around your problem by writing a wrapper instead of asking for drastic core changes. 
that said if you have further questions about using löve you should use the forums or discord

**Comment by roroire** [comment]
I didn't ask a specific implementation of vectors itself, but rather that arguments would use tables with x and y values, so any vector library would work once the dev sets its x and y value on their vectors

writing a wrapper for the whole of physics and draw seems like a big waste of time for what should be a simple feature, also, the body thing is still a problem: on :setLinearVelocity(), velocity changes, so the original table which defined position becomes outdated, and then simply setting the new table's position doesn't work anymore, one would have to use :getPosition() on the Body and then the
original position table would become useless, unless the dev creates variables to show the differences, or if the dev remakes :setLinearVelocity(), 

then, why to recreate two modules, when the default could be simple and compatible?

also, receiving one variable is better than receiving the same variable buta s two, as it avoids errors my mistyping, speeding up development,

and well, it's not that drastic if it is retro-compatible, it's only extensible as the modules are huge,

and hey, a curiosity, why one ought to use :getX() and may not just get .x? is because getX() is directly binded to SDL2 and it would convert from whatever language SDL2 uses?,

and I won't use the forum, it uses ancient-looking interface, that ain't accessibility-minded at all, it is not Discourse nor Flarum,

and I won't use Discord, I avoid proprietary as much as I can, and in good will I loged in Github for this project,

and last, I do not have "questions", I have an issue with an enhancement proposal

**Comment by a13X-B** [comment]
there are implementations of vectors that use x and y for components, then there are 1-indexed tables as per lua array conventions, and there are 0-indexed arrays as per ffi conventions.
you're asking the devs to write that aforementioned wrapper for you and force it on the entire userbase.
still if you have any further questions it's better to ask those in a more appropriate place, such as love forums or discord

**Comment by slime73** [comment]
This github issue tracker is for bug reports and feature requests, rather than general discussion or support. If you don't want to engage in the places that are appropriate for discussion/support that's up to you, but it doesn't make this a valid place for it.

That being said, this is a feature request as it's written.

Unfortunately Lua as a language requires tradeoffs when using vector structures. Creating a new vector allocates memory that will be garbage-collected (which impacts performance). There are ways to reuse rather than creating new ones, but they tend to make APIs less friendly to use. As mentioned above there are also different possible conventions for how a vector's components are accessed etc.

By taking individual vector components as parameters (and as return values), love's APIs bypass those issues by letting you write your code how you want and it just needs to pass along components when interfacing with love. If it forced you to pass in a vector object it would require the above tradeoffs and more. Adding function variants that take both would add too much bloat to love's APIs, so that's not really viable either.

I expect once we have a C API (#1640) people will start creating bindings to languages that are friendlier to vector objects, and you'll probably see love's APIs take them directly in those situations. But for now with Lua, we haven't found a good way to have them directly in the API that doesn't introduce problems we'd like to avoid.

**Comment by roroire** [comment]
@slime73, oh, I didn't thought of here as a feature request, but _enhancement_, which I think is similar to feature request;

anyway, I'm sorry for looking at the wrong place, I am used for enhancements as a place to be in Github,

> by letting you write your code however you want
not exactly, as the arguments from love.graphics.rectangle must be written in certain long order, and given that those functions are that long...

> adding function variants
no, I mean more like the same function, with "if argument 2 is a table, then get argument 2's x"

@a13X-B, thank you for mentioning that there are vector implementations that use number indexes, but that doesn't break anything if there's retrocompatibility

now, stop recommending love forums and Discord to to me, I already said no

I won't insist on this topic anymore, I just wanted to point these things
