### ISSUE TITLE
Cannot load .dll from app folder, but does work when loading from framework folder.

### ISSUE THREAD

**Issue by simonpuravida333** [love2d/love#2120]
I described it already here: https://www.love2d.org/forums/viewtopic.php?p=261175#p261175

Maybe love thinks the .dll is incompatible. Because that error log line "C library 'lua-utf8' is incompatible" among all the other loading error log lines doesn't appear when it just can't find the file. (Could you update the error log to only show the message of incompatible in such case?)

Since I can load it from the framework folder, I'm good. But it seems you want to allow loading .dlls from anywhere, just like any other file (which would be cool), hence this post.
I also loaded the dll into a (non-love) luajit app and it worked fine.

**Comment by slime73** [comment]
Operating systems can't load dlls that are within zip/.love files, so if you put it at the root of your project folder you'd still have a problem when distributing it.

That being said, if you've put it in a subfolder that also won't work for loading because of how the function entry point is resolved.

I recommend using love.filesystem to copy it to the root of the save directory when your game loads.

**Comment by slime73** [comment]
If you copy it to the root of the save directory it should work fine in any sort of build (as long as you copy the right architecture's dll).

**Comment by simonpuravida333** [comment]
thx. good to know :)
