### ISSUE TITLE
Can't find ssl.http module on macosx build.

### ISSUE THREAD

**Issue by myzhan** [love2d/love#2129]
I try to compile love2d in xcode with  love-apple-dependencies, and require socket.http module.

```bash
Error: [string "socket.http"]:39: module 'ssl.https' not found:
	no field package.preload['ssl.https']
	no 'ssl/https' in LOVE game directories.
	no file 'ssl/https' in LOVE paths.
	no file './ssl/https.lua'
	no file '/usr/local/share/luajit-2.1/ssl/https.lua'
	no file '/usr/local/share/lua/5.1/ssl/https.lua'
	no file '/usr/local/share/lua/5.1/ssl/https/init.lua'
	no file './ssl/https.so'
	no file '/usr/local/lib/lua/5.1/ssl/https.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './ssl.so'
	no file '/usr/local/lib/lua/5.1/ssl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

It seems that love2d has not builtin support. Should I install luasec with lua5.1?

**Comment by slime73** [comment]
love provide luasocket, whereas luasec is a separate thing which extends luasocket, and love doesn't provide that. I heavily recommend the [lua-https](https://love2d.org/wiki/lua-https) module (provided by love 12 or as a standalone dll download for love 11) instead of luasec, since luasec is difficult to bundle with an app, but you can also try it if you want.
