### ISSUE TITLE
Add SSL/TLS APIs

### ISSUE THREAD

**Issue by slime73** [love2d/love#368]
**[Original report](https://bitbucket.org/rude/love/issue/363) by Linus (Bitbucket: [thelinx](https://bitbucket.org/thelinx), GitHub: [thelinx](https://github.com/thelinx)).**

----------------------------------------

We already have LuaSocket, so why not add support for SSL-protected networking as well?

**Comment by MikuAuahDark** [comment]
I'm also facing technical difficulties of finding best way to provide SSL/TLS in LOVE Android.

When LuaSec + LibreSSL approach is used, that means we have access to LuaSec which is most popular TLS library for Lua. The disadvantages is user have to ship their own CA, and if vulnerability is found under LibreSSL used, users have to wait for next LOVE version for the vulnerability to be fixed.

That's why I prefer if the TLS functionality is provided by the OS, because users only need to update their OS to get the vulnerability fixed. However, different OS have different TLS libraries, and the worse is Android because the `SSLSocket` is Java-only. Furthermore, it's not possible to wrap the socket like LuaSec at all because `SSLSocket` class is completely have to be done from Java side. You may ask, why not pass the LuaSocket's `:getfd()`? The answer is the Java side has no way of accepting integer file descriptor, eliminating the idea of "wrapping the socket".

One thing is possible is if we only use TLS for HTTPS. In that case, JNI can be used to communicate since we didn't do any socket wrapping, but completely doing the connection from Java side. However, as sharpobject mentioned, TLS + custom protocol is not possible with it.

Better approach is always welcome.

**Comment by ParticleG** [comment]
I compiled luasec with openssl into one single dll/so on multiple platforms with widely used architectures. Tested on windows, Linux, Mac, android and ios. May be this would help.
https://github.com/26F-Studio/love-luasec

**Comment by slime73** [comment]
12.0 now has an HTTPS lua module, via 81791a3.
